using Domain.Notifications;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;

namespace Infrastructure.Notifications;

public sealed class NotificationTemplateSeeder(ApplicationDbContext dbContext)
{
    public async Task SeedAsync(CancellationToken cancellationToken)
    {
        await UpsertAsync(
            NotificationTemplateCatalog.AlertIncidentEmail,
            NotificationChannel.Email,
            "fa-IR",
            "هشدار سامانه - {{RuleName}}",
            """
            <div style="font-family:Tahoma,Segoe UI,sans-serif;line-height:1.8;color:#1F2937">
              <h2 style="margin:0 0 12px 0;color:#B91C1C">هشدار جدید در سامانه ثبت شد</h2>
              <p>سلام {{AdminDisplayName}}،</p>
              <p>یک رخداد هشدار جدید توسط موتور لاگ تشخیص داده شد.</p>
              <table style="border-collapse:collapse;width:100%;max-width:760px">
                <tr><td style="padding:6px 8px;border:1px solid #E5E7EB"><strong>Rule</strong></td><td style="padding:6px 8px;border:1px solid #E5E7EB">{{RuleName}}</td></tr>
                <tr><td style="padding:6px 8px;border:1px solid #E5E7EB"><strong>IncidentId</strong></td><td style="padding:6px 8px;border:1px solid #E5E7EB">{{IncidentId}}</td></tr>
                <tr><td style="padding:6px 8px;border:1px solid #E5E7EB"><strong>EventId</strong></td><td style="padding:6px 8px;border:1px solid #E5E7EB">{{EventId}}</td></tr>
                <tr><td style="padding:6px 8px;border:1px solid #E5E7EB"><strong>Severity</strong></td><td style="padding:6px 8px;border:1px solid #E5E7EB">{{Severity}}</td></tr>
                <tr><td style="padding:6px 8px;border:1px solid #E5E7EB"><strong>TriggeredAtUtc</strong></td><td style="padding:6px 8px;border:1px solid #E5E7EB">{{TriggeredAtUtc}}</td></tr>
                <tr><td style="padding:6px 8px;border:1px solid #E5E7EB"><strong>Source</strong></td><td style="padding:6px 8px;border:1px solid #E5E7EB">{{SourceService}} / {{SourceModule}}</td></tr>
                <tr><td style="padding:6px 8px;border:1px solid #E5E7EB"><strong>Message</strong></td><td style="padding:6px 8px;border:1px solid #E5E7EB">{{Message}}</td></tr>
                <tr><td style="padding:6px 8px;border:1px solid #E5E7EB"><strong>TraceId</strong></td><td style="padding:6px 8px;border:1px solid #E5E7EB">{{TraceId}}</td></tr>
                <tr><td style="padding:6px 8px;border:1px solid #E5E7EB"><strong>Outcome</strong></td><td style="padding:6px 8px;border:1px solid #E5E7EB">{{Outcome}}</td></tr>
              </table>
              <p style="margin-top:14px">لطفا بررسی لازم انجام شود.</p>
            </div>
            """,
            cancellationToken);

        await UpsertAsync(
            NotificationTemplateCatalog.UserRegistrationVerificationEmail,
            NotificationChannel.Email,
            "fa-IR",
            "تایید ثبت نام - {{AppName}}",
            """
            <div style="font-family:Tahoma,Segoe UI,sans-serif;line-height:1.8;color:#1F2937">
              <h2 style="margin:0 0 12px 0;color:#0F766E">ثبت نام شما با موفقیت انجام شد</h2>
              <p>سلام {{FirstName}} {{LastName}}،</p>
              <p>برای تکمیل ثبت‌نام، کد تایید زیر را وارد کنید:</p>
              <div style="margin:16px 0;padding:14px 16px;background:#F0FDFA;border:1px solid #99F6E4;border-radius:8px;font-size:24px;letter-spacing:4px;font-weight:700;display:inline-block">
                {{VerificationCode}}
              </div>
              <p>این کد تا <strong>{{ExpiresAtUtc}}</strong> معتبر است.</p>
              <p>اگر شما درخواست ثبت‌نام نداده‌اید، این پیام را نادیده بگیرید.</p>
              <hr style="border:none;border-top:1px solid #E5E7EB;margin:18px 0" />
              <small style="color:#6B7280">Generated by {{AppName}}</small>
            </div>
            """,
            cancellationToken);

        await UpsertAsync(
            NotificationTemplateCatalog.UserPasswordResetEmail,
            NotificationChannel.Email,
            "fa-IR",
            "Reset password - {{AppName}}",
            """
            <div style="font-family:Tahoma,Segoe UI,sans-serif;line-height:1.8;color:#1F2937">
              <h2 style="margin:0 0 12px 0;color:#0F766E">Password reset request</h2>
              <p>Hello {{FirstName}} {{LastName}},</p>
              <p>Use the following code to reset your password:</p>
              <div style="margin:16px 0;padding:14px 16px;background:#EFF6FF;border:1px solid #BFDBFE;border-radius:8px;font-size:24px;letter-spacing:4px;font-weight:700;display:inline-block">
                {{ResetCode}}
              </div>
              <p>This code is valid until <strong>{{ExpiresAtUtc}}</strong>.</p>
              <p>If you did not request this change, ignore this email.</p>
              <hr style="border:none;border-top:1px solid #E5E7EB;margin:18px 0" />
              <small style="color:#6B7280">Generated by {{AppName}}</small>
            </div>
            """,
            cancellationToken);
    }

    private async Task UpsertAsync(
        string name,
        NotificationChannel channel,
        string language,
        string subjectTemplate,
        string bodyTemplate,
        CancellationToken cancellationToken)
    {
        NotificationTemplate? existing = await dbContext.NotificationTemplates
            .SingleOrDefaultAsync(
                x => x.Name == name && x.Channel == channel && x.Language == language,
                cancellationToken);

        if (existing is null)
        {
            NotificationTemplate entity = new()
            {
                Id = Guid.NewGuid(),
                Name = name,
                Channel = channel,
                Language = language,
                SubjectTemplate = subjectTemplate,
                BodyTemplate = bodyTemplate,
                Version = 1,
                CreatedAtUtc = DateTime.UtcNow
            };

            dbContext.NotificationTemplates.Add(entity);
            dbContext.NotificationTemplateRevisions.Add(new NotificationTemplateRevision
            {
                Id = Guid.NewGuid(),
                TemplateId = entity.Id,
                Version = entity.Version,
                SubjectTemplate = entity.SubjectTemplate,
                BodyTemplate = entity.BodyTemplate,
                CreatedAtUtc = DateTime.UtcNow,
                ChangedByUserId = null
            });

            await dbContext.SaveChangesAsync(cancellationToken);
            return;
        }

        if (existing.SubjectTemplate == subjectTemplate &&
            existing.BodyTemplate == bodyTemplate &&
            !existing.IsDeleted)
        {
            return;
        }

        existing.SubjectTemplate = subjectTemplate;
        existing.BodyTemplate = bodyTemplate;
        existing.IsDeleted = false;
        existing.Version++;
        existing.UpdatedAtUtc = DateTime.UtcNow;

        dbContext.NotificationTemplateRevisions.Add(new NotificationTemplateRevision
        {
            Id = Guid.NewGuid(),
            TemplateId = existing.Id,
            Version = existing.Version,
            SubjectTemplate = existing.SubjectTemplate,
            BodyTemplate = existing.BodyTemplate,
            CreatedAtUtc = DateTime.UtcNow,
            ChangedByUserId = null
        });

        await dbContext.SaveChangesAsync(cancellationToken);
    }
}
