// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class AddLoggingPlatform : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "AlertIncidents",
                schema: "dbo",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    RuleId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    TriggerEventId = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    TriggeredAtUtc = table.Column<DateTime>(type: "datetime2", nullable: false),
                    Status = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    RetryCount = table.Column<int>(type: "int", nullable: false),
                    NextRetryAtUtc = table.Column<DateTime>(type: "datetime2", nullable: true),
                    LastError = table.Column<string>(type: "nvarchar(2000)", maxLength: 2000, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AlertIncidents", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "AlertRules",
                schema: "dbo",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Name = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    IsEnabled = table.Column<bool>(type: "bit", nullable: false),
                    MinimumLevel = table.Column<int>(type: "int", nullable: false),
                    ContainsText = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                    WindowSeconds = table.Column<int>(type: "int", nullable: false),
                    ThresholdCount = table.Column<int>(type: "int", nullable: false),
                    Action = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    CreatedAtUtc = table.Column<DateTime>(type: "datetime2", nullable: false),
                    UpdatedAtUtc = table.Column<DateTime>(type: "datetime2", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AlertRules", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "LogEvents",
                schema: "dbo",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    IdempotencyKey = table.Column<string>(type: "nvarchar(120)", maxLength: 120, nullable: true),
                    TimestampUtc = table.Column<DateTime>(type: "datetime2", nullable: false),
                    Level = table.Column<int>(type: "int", nullable: false),
                    Message = table.Column<string>(type: "nvarchar(4000)", maxLength: 4000, nullable: false),
                    SourceService = table.Column<string>(type: "nvarchar(150)", maxLength: 150, nullable: false),
                    SourceModule = table.Column<string>(type: "nvarchar(150)", maxLength: 150, nullable: false),
                    TraceId = table.Column<string>(type: "nvarchar(150)", maxLength: 150, nullable: false),
                    RequestId = table.Column<string>(type: "nvarchar(150)", maxLength: 150, nullable: true),
                    TenantId = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    ActorType = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    ActorId = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    Outcome = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    SessionId = table.Column<string>(type: "nvarchar(150)", maxLength: 150, nullable: true),
                    Ip = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: true),
                    UserAgent = table.Column<string>(type: "nvarchar(1000)", maxLength: 1000, nullable: true),
                    DeviceInfo = table.Column<string>(type: "nvarchar(1000)", maxLength: 1000, nullable: true),
                    HttpMethod = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    HttpPath = table.Column<string>(type: "nvarchar(1000)", maxLength: 1000, nullable: true),
                    HttpStatusCode = table.Column<int>(type: "int", nullable: true),
                    ErrorCode = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                    ErrorStackHash = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    TagsCsv = table.Column<string>(type: "nvarchar(2000)", maxLength: 2000, nullable: true),
                    PayloadJson = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false),
                    DeletedAtUtc = table.Column<DateTime>(type: "datetime2", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_LogEvents", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_AlertIncidents_RuleId",
                schema: "dbo",
                table: "AlertIncidents",
                column: "RuleId");

            migrationBuilder.CreateIndex(
                name: "IX_AlertIncidents_Status",
                schema: "dbo",
                table: "AlertIncidents",
                column: "Status");

            migrationBuilder.CreateIndex(
                name: "IX_AlertIncidents_TriggeredAtUtc",
                schema: "dbo",
                table: "AlertIncidents",
                column: "TriggeredAtUtc");

            migrationBuilder.CreateIndex(
                name: "IX_AlertRules_Name",
                schema: "dbo",
                table: "AlertRules",
                column: "Name",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_LogEvents_ActorId",
                schema: "dbo",
                table: "LogEvents",
                column: "ActorId");

            migrationBuilder.CreateIndex(
                name: "IX_LogEvents_IdempotencyKey",
                schema: "dbo",
                table: "LogEvents",
                column: "IdempotencyKey",
                unique: true,
                filter: "[IdempotencyKey] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_LogEvents_Level",
                schema: "dbo",
                table: "LogEvents",
                column: "Level");

            migrationBuilder.CreateIndex(
                name: "IX_LogEvents_SourceService",
                schema: "dbo",
                table: "LogEvents",
                column: "SourceService");

            migrationBuilder.CreateIndex(
                name: "IX_LogEvents_TimestampUtc",
                schema: "dbo",
                table: "LogEvents",
                column: "TimestampUtc");

            migrationBuilder.CreateIndex(
                name: "IX_LogEvents_TraceId",
                schema: "dbo",
                table: "LogEvents",
                column: "TraceId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AlertIncidents",
                schema: "dbo");

            migrationBuilder.DropTable(
                name: "AlertRules",
                schema: "dbo");

            migrationBuilder.DropTable(
                name: "LogEvents",
                schema: "dbo");
        }
    }
}
